# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reference_id',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Reference ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='reference_id',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Reference ID'),
            preserve_default=False,
        ),
    ]
